Fix: Command/args/inputs handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/tox-extract-config-action/action.yaml b/.github/actions/tox-extract-config-action/action.yaml
--- a/.github/actions/tox-extract-config-action/action.yaml
+++ b/.github/actions/tox-extract-config-action/action.yaml
@@ -21,12 +21,12 @@ inputs:
     description: "TOX environment to query"
     type: string
     required: false
-  AWK_COMMAND:
-    description: "AWK command to manipulate returned value"
+  AWK_ARGS:
+    description: "AWK arguments to manipulate returned value"
     type: string
     required: false
-  SED_COMMAND:
-    description: "SED command to manipulate returned value"
+  SED_ARGS:
+    description: "SED arguments to manipulate returned value"
     type: string
     required: false
 
@@ -44,34 +44,45 @@ runs:
       run: |
         # 🔍 Parse TOX configuration file
 
+        PYTHON_CMD=$(which python)
+        if [ ! -x $PYTHON_CMD ]; then
+          echo "Unable to run Python command ❌"
+          echo "Call setup-python before calling"
+          exit 1
+        fi
+
         TOX_CMD=$(which tox)
-        if [ ! -x $PIP_CMD ]; then
+        if [ ! -x $TOX_CMD ]; then
+          "$PYTHON_CMD" -m venv /tmp/tox
           if ! (pip install --upgrade --disable-pip-version-check -q tox > /dev/null); then
-            echo "Unable to find/install tox command ❌"; exit 1
+            echo "Unable to use pip to install tox command ❌"; exit 1
           else
-            echo "Successfully installed tox ✅"
+            echo "Successfully installed tox in virtual environment ✅"
           fi
           TOX_CMD=$(which tox)
         fi
 
-        # If optional inputs are specified, add the necessary commands, etc.
+        # Process optional inputs
         if [ -n ${{ inputs.TOX_ENVIRONMENT }} ]; then
           TOX_ENV_STRING="-e${{ inputs.TOX_ENVIRONMENT }}"
         fi
-        if [ -n ${{ inputs.AWK_COMMAND }} ]; then
-          AWK_STRING="| ${{ inputs.AWK_STRING }}"
-        fi
-        if [ -n ${{ inputs.SED_COMMAND }} ]; then
-          SED_STRING="| ${{ inputs.SED_STRING }}"
-        fi
+        set -o noglob
+        AWK_ARGS="${{ inputs.AWK_ARGS }}"
+        SED_ARGS="sed ${{ inputs.SED_ARGS }}"
+        set +o noglob
 
         # Build shell command
         # e.g. tox config -c docs/tox.ini -edocs | grep base_python | awk '{print $3}' | sed "s:python::g"
         TOX_COMMAND="$TOX_CMD config -c ${{ inputs.TOX_CONFIG_PATH }} $TOX_ENV_STRING"
-
         echo "TOX command: $TOX_COMMAND"
-        echo "Full shell command: $TOX_COMMAND $AWK_STRING $SED_STRING"
-        RETURN_VALUE=$($TOX_COMMAND $AWK_STRING $SED_STRING)
+        TOX_OUTPUT=$($TOX_COMMAND)
+
+        if [ -n "$AWK_ARGS" ]; then
+          RETURN_VALUE=$(echo "$TOX_OUTPUT" | awk $AWK_ARGS)
+        fi
+        if [ -n "$SED_ARGS" ]; then
+          RETURN_VALUE=$(echo "$RETURN_VALUE" | sed $SED_ARGS)
+        fi
 
         # Report/return results
         if [ -z "$RETURN_VALUE" ]; then
